/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fdfcf8',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'on-surface': '#0f1e33',
        'on-surface-variant': '#4a5568',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4ff',
        'surface-container': '#e6edff',
        'surface-container-high': '#d9e6ff',
        'surface-container-highest': '#cfe0ff',
        'surface-variant': '#d3e4fe',
        'inverse-surface': '#1a2a44',
        'inverse-on-surface': '#eaf1ff',
        primary: '#131b2e',
        'on-primary': '#ffffff',
        'primary-container': '#1e2e4a',
        'on-primary-container': '#cbd5e1',
        secondary: '#00a86b',
        'on-secondary': '#ffffff',
        'secondary-container': '#d1fae5',
        'on-secondary-container': '#065f46',
        // Duolingo vibrant system — used for Chunky 3D buttons & accents
        duo: {
          green: '#58cc02',
          'green-shadow': '#46a302',
          'green-press': '#3d8a00',
          blue: '#1cb0f6',
          'blue-shadow': '#1493cf',
          yellow: '#ffc800',
          'yellow-shadow': '#e5b500',
          orange: '#ff9600',
          'orange-shadow': '#e68600',
          red: '#ff4b4b',
          'red-shadow': '#e04343',
        },
        accent: '#ffc800',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        outline: '#8a8f98',
        'outline-variant': '#d8dee8',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
